version: "3.8"

services:
  strapi-db:
    image: postgres:15-alpine
    container_name: strapi-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: strapi_user
      POSTGRES_PASSWORD: strapi_password
      POSTGRES_DB: strapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - strapi-net


  strapi-app:
    build: .
    container_name: strapi-app
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: strapi-db
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi_db
      DATABASE_USERNAME: strapi_user
      DATABASE_PASSWORD: strapi_password
      NODE_ENV: production
      APP_KEYS: testKey1,testKey2
      API_TOKEN_SALT: testSalt
      ADMIN_JWT_SECRET: testSecret
      TRANSFER_TOKEN_SALT: testTransfer
      JWT_SECRET: anotherTestSecret
    depends_on:
      - strapi-db
    networks:
      - strapi-net

  strapi-proxy:
    image: nginx:alpine
    container_name: strapi-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - strapi-app
    networks:
      - strapi-net

networks:
  strapi-net:
    name: strapi-net
    driver: bridge

volumes:
  postgres_data:
